관리자 강의 목록 페이지 구현완료
711skhu/front_admin pull request #10
Opened 2019-06-09 13:15 UTC by jeenie

1. 강의 목록 전체 페이지
    * 로그인한 사용자(교수)의 담당 과목 목록 출력 구현
    * toggle 버튼 -> 활성화 여부
    * 강의 목록 생성 컴포넌트 구현
<img width="931" alt="관리자 강의목록 페이지1" src="https://user-images.githubusercontent.com/38181303/59159292-84758300-8b02-11e9-8bac-24a07c34d880.png">
<img width="936" alt="관리자 강의목록 페이지2" src="https://user-images.githubusercontent.com/38181303/59159294-86d7dd00-8b02-11e9-8a72-25d5c0ca99da.png">

2. 강의명 공백
   * 알림창 구현
<img width="734" alt="강의명 공백 상태" src="https://user-images.githubusercontent.com/38181303/59159312-ddddb200-8b02-11e9-90d1-067b83b0e02d.png">
 
3. 강의명 중복 x
    * 강의 추가 가능 상태 표시
<img width="698" alt="강의명 정상" src="https://user-images.githubusercontent.com/38181303/59159354-69efd980-8b03-11e9-9279-704b3941ba39.png">

4. 강의명 중복o
    * 강의 추가 불가능 상태 
<img width="677" alt="강의명 중복" src="https://user-images.githubusercontent.com/38181303/59159381-c2bf7200-8b03-11e9-9211-1a3ef398298f.png">

2019-06-09 13:43 UTC, shouwn requested changes

2019-06-09 13:43 UTC, shouwn commented on views/lectureList/LectureAdd.vue
> +    props: ['lectures'],
props 는 타입과 설명을 꼭 추가해주세요.

2019-06-09 13:43 UTC, shouwn commented on views/lectureList/LectureAdd.vue
> +      }
props 로 받은 배열을 수정하는 메소드인데요. 절대 자식이 부모한테서 받은 것을 수정하거나 조작하면 안 됩니다.

이 경우 부모한테 event를 발생시켜 부모 측에서 lectures 에 추가하도록 코드를 수정하여야 합니다.

2019-06-09 13:43 UTC, shouwn commented on views/lectureList/LectureList.vue
> +    props: ['lectures'],
위와 마찬가지로 props 는 타입과 설명이 있어야 합니다.

2019-06-09 13:43 UTC, shouwn commented on views/lectureList/LectureList.vue
> +          console.log(this.isProfessor);
테스트 용 코드는 PR할 때 제거해주세요.

2019-06-09 13:43 UTC, shouwn commented on views/lectureList/LectureList.vue
> +        isProfessor: false
어드민 쪽은 항상 어드민만 접속할 수 있기 때문에 isProfessor와 같이 재확인할 필요가 없습니다.

2019-06-09 13:43 UTC, shouwn commented on views/lectureList/LectureListPage.vue
> +    <lecture-add :lectures="lectures"></lecture-add>
이름으로 add 보다는 adder는 어떤가요?

2019-06-09 13:43 UTC, shouwn commented on views/lectureList/LectureListPage.vue
> +          console.log(this.lectures);
lecture 모델을 정의하는 것도 좋을 것 같습니다.

이 경우 서버 쪽에서는 주는 코드가 수정되면 모든 컴포넌트가 다 영향을 받기 때문입니다.

서버 쪽 API가 완성되면 할 것이었지만 axios를 적용하셔서 말씀드리면, 서버 쪽에서 준 객체를 그대로 사용하는 것이 아니라 저희들이 정의한 모델 객체로 수정해서 넣고 그걸 통해서 우리가 뷰로 보여주어야 합니다.

2019-06-09 17:54 UTC, jihyuno301 commented on views/lectureList/LectureAdd.vue
> +        <div class="header">Action Forbidden</div>
강의 생성 가능/불가능 여부를 어떻게 확인가능한건가요?

2019-06-11 03:42 UTC, jeenie commented on views/lectureList/LectureAdd.vue
> +        <div class="header">Action Forbidden</div>
게시한 동영상에 보시면 입력 하단에 상태메시지가 뜹니다...

2019-06-11 04:03 UTC, jeenie commented on views/lectureList/LectureAdd.vue
> +        <div class="header">Action Forbidden</div>
코드 업데이트 하겠습니다!

2019-06-11 08:28 UTC, shouwn commented on views/lectureList/LectureList.vue
> +        lectures: this.lectures
props 로 받은 것은 data 처럼 추적을 하기 때문에 이 문장은 필요 없습니다.

2019-06-11 08:28 UTC, shouwn commented on views/lectureList/LectureAdder.vue
> +        this.$emit('child-event', this.newLectureName)
child-event라는 이름 보다는 좀 더 행위를 나타내는 이름이 좋을 것 같아요.

2019-06-11 10:02 UTC, shouwn approved these changes

2019-06-22 11:29 UTC, merged