문제 리스트 페이지 구현
711skhu/front_admin pull request #3
Opened 2019-05-22 15:19 UTC by shouwn

이미지가 잘 안 보이면 클릭해서 확대해주세요.

![image](https://user-images.githubusercontent.com/31586979/58186692-59142b00-7cf0-11e9-90af-d022575aa0cd.png)

![image](https://user-images.githubusercontent.com/31586979/58186657-4994e200-7cf0-11e9-9362-1e21e99cc16b.png)

2019-05-23 12:34 UTC, jeenie commented
각 문제 우측에 '제출한 인원 / 총 수강 학생' 이 있으면 어떨까요?

2019-05-23 12:37 UTC, jeenie commented
첫번째 사진에서 그림자 효과 ˇ 이부분도 포함되면 좋을거 같습니다!

2019-05-23 12:43 UTC, shouwn commented
현재 ProblemItemBox에 그림자 효과를 주고 그것을 expansion-panel의 header로 주는 방식으로 구현했는데요. 이 방식으로는  ˇ 부분까지 그림자 효과가 미치지 못 합니다. ㅠㅠ 

만약  ˇ 까지 그림자 효과를 만드려면 ProblemItemBox를 사용하지 않고 expansion-panel 겉에 그림자 효과를 주면 되는데 이렇게 구현하는 것이 더 좋을까요?

2019-05-23 12:46 UTC, shouwn commented
@jeenie 좋은 생각입니다.

2019-05-23 12:56 UTC, jeenie requested changes
회의결과: 각 문제 아이템 우측에 '제출한 인원 / 총 수강 학생'(vutify 회전 사용) '성적보기' 버튼 을 구성.
문제 아이템을 클릭하면 문제를 볼수 있는 페이지로 이동한다.

2019-05-24 07:47 UTC, shouwn commented
## 수정 이미지

![image](https://user-images.githubusercontent.com/31586979/58311236-74dc1600-7e43-11e9-9e59-a701309def65.png)
![image](https://user-images.githubusercontent.com/31586979/58311249-7dcce780-7e43-11e9-8a9e-443a09f59f27.png)
![image](https://user-images.githubusercontent.com/31586979/58311271-86bdb900-7e43-11e9-904c-b91c893e51c1.png)
![image](https://user-images.githubusercontent.com/31586979/58311284-8e7d5d80-7e43-11e9-8d6a-e6ee16999033.png)

2019-05-24 07:51 UTC, jeenie reviewed
새로고침 버튼과 그래프(?)의 위치를 바꾸면 어떨까요???

2019-05-24 07:52 UTC, jeenie reviewed
문제 아이템에 오버를 하면 그래프 안이 '목록' 아이콘으로 변경되는거 멋져요!!!! :)

2019-05-24 07:55 UTC, jeenie reviewed
제출한 학생의 목록 펼쳐 보는거에서 테이블의 테두리 구분선(?) 이 없으면 더 깔끔해보일거 같습니다.
<img width="583" alt="58311271-86bdb900-7e43-11e9-904c-b91c893e51c1" src="https://user-images.githubusercontent.com/38181303/58311751-ae615100-7e44-11e9-8edd-b3c0b04f4742.png">
(빨간색 안 테이블의 테두리!)

2019-05-24 08:00 UTC, jeenie approved these changes

2019-05-24 08:01 UTC, shouwn commented
@jeenie 빨간색 안에 테두리는 아쉽게도 Vuetify 거라서 제가 건들 수가 없네요. ㅠㅠ

새로고침 버튼 위치를 바꾸면 아래와 같이 되는데 이게 더 좋나요?

![image](https://user-images.githubusercontent.com/31586979/58312057-7c042380-7e45-11e9-821c-52578f865c25.png)

2019-05-24 08:04 UTC, jeenie commented
@shouwn 오 저는 좋아요!!! 아쉽지만 어쩔수 없네여 ㅠㅠ

2019-05-28 08:08 UTC, merged